Repository FUB-HCC/20-SWP-CodingOpenness, pull requests merged in 2020-05, with the labels that each got.

#46 fetch Vergleich.md content once ComponentDidMount
  project-website/src/Components/Vergleich/Vergleich.js
  project-website/src/Markdown/Vergleich.md
Labels: Projektwebseite

#45 Merge project-website to master
  project-website/.gitignore
  project-website/README.md
  project-website/package-lock.json
  project-website/package.json
  project-website/public/HCC.jpeg
  project-website/public/favicon.ico
  project-website/public/index.html
  project-website/public/logo192.png
  project-website/public/logo512.png
  project-website/public/manifest.json
  project-website/public/robots.txt
  project-website/src/App.css
  project-website/src/App.js
  project-website/src/Assets/HCC.jpeg
  project-website/src/Assets/fu-logo.png
  project-website/src/Assets/github.svg
  project-website/src/Assets/hcc-logo.png
  project-website/src/Components/About/About.js
  project-website/src/Components/Groups/Groups.css
  project-website/src/Components/Groups/Groups.js
  project-website/src/Components/Home/Home.css
  project-website/src/Components/Home/Home.js
  project-website/src/Components/Vergleich/Vergleich.js
  project-website/src/Markdown/Vergleich.md
  project-website/src/index.css
  project-website/src/index.js
  project-website/src/logo.svg
  project-website/src/serviceWorker.js
  project-website/src/setupTests.js
  project-website/yarn.lock
Labels: Projektwebseite

#47 change `Gruppen` tab to `Ansaetze`
  project-website/.gitignore
  project-website/src/App.js
  project-website/src/Components/Ansaetze/Ansaetze.css
  project-website/src/Components/Ansaetze/Ansaetze.js
  project-website/src/Components/Home/Home.js
Labels: Projektwebseite

#55 Markdown für Vergleich auf Webseite aktualiseren
  src/Markdown/Vergleich.md
Labels: Blocker, Vergleich

#63 added contact info
  package-lock.json
  src/Components/About/About.js
  src/Components/Kontakt/Kontakt.css
  src/Components/Kontakt/Kontakt.js
Labels: Projektwebseite

#61 Polish contact form - using emailjs
  package-lock.json
  package.json
  src/.Rhistory
  src/App.js
  src/Components/About/About.js
  src/Components/Kontakt/Kontakt.css
  src/Components/Kontakt/Kontakt.js
Labels: Medium, Projektwebseite, size-M

#87 add description to icon links
  src/Components/About/About.js
  src/Components/Ansaetze/Ansaetze.js
Labels: Projektwebseite

#88 revised about view
  src/Components/About/About.css
  src/Components/About/About.js
Labels: Projektwebseite

#89 Website/feat/background colors
  src/App.js
  src/Assets/a.png
  src/Components/About/About.css
  src/Components/About/About.js
  src/Components/Ansaetze/Ansaetze.css
  src/Components/Ansaetze/Ansaetze.js
Labels: Projektwebseite

#90 Website/feat/header navbar
  src/App.css
  src/App.js
  src/Assets/a.png
  src/Assets/hcc-logo-white.png
  src/Assets/hcc-logo.png
  src/Components/About/About.css
  src/Components/About/About.js
  src/Components/Ansaetze/Ansaetze.css
  src/Components/Ansaetze/Ansaetze.js
  src/Components/Home/Home.css
  src/Components/Home/Home.js
  src/Components/Kontakt/Kontakt.css
  src/Components/Kontakt/Kontakt.js
  src/Components/Vergleich/Vergleich.js
  src/index.css
Labels: Projektwebseite
