Repository FUB-HCC/20-SWP-CodingOpenness, pull requests merged in 2020-06, with the labels that each got.

#97 changed contact page styling & removed emailjs for the time being
  package-lock.json
  package.json
  src/Components/Home/Home.js
  src/Components/Kontakt/Kontakt.css
  src/Components/Kontakt/Kontakt.js
Labels: Projektwebseite

#115 added css media query to allow website interactivity for smaller screens
  src/App.css
  src/App.js
  src/Components/About/About.css
  src/Components/About/About.js
  src/Components/Ansaetze/Ansaetze.css
  src/Components/Ansaetze/Ansaetze.js
  src/Components/Home/Home.css
  src/Components/Home/Home.js
  src/Components/Kontakt/Kontakt.css
  src/Components/Kontakt/Kontakt.js
  src/Components/Vergleich/Vergleich.css
  src/Components/Vergleich/Vergleich.js
Labels: Projektwebseite

#96 Ansaetze sticky navbar fix and Kontakt change of origin email address
  src/Components/Ansaetze/Ansaetze.css
  src/Components/Ansaetze/Ansaetze.js
Labels: Projektwebseite, size-XXS

#128 fragebogen tab and content added
  src/App.js
  src/Assets/dcts.png
  src/Assets/pepp-pt.png
  src/Components/About/About.css
  src/Components/Ansaetze/Ansaetze.css
  src/Components/Ansaetze/Ansaetze.js
  src/Components/Fragebogen/Fragebogen.css
  src/Components/Fragebogen/Fragebogen.js
  src/Components/Home/Home.css
  src/Components/Home/Home.js
  src/Components/Kontakt/Kontakt.css
  src/Components/Kontakt/Kontakt.js
  src/Components/Vergleich/Vergleich.css
  src/Markdown/Vergleich.md
Labels: Projektwebseite

#142 footer fix
  public/index.html
  src/App.css
  src/App.js
  src/Components/About/About.js
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
  src/Components/Home/Home.css
  src/Components/Vergleich/Vergleich.css
  src/index.css
Labels: Projektwebseite

#143 further clean up and re-organization of css on Ansaetze, Vergleich, About.
  src/Components/About/About.css
  src/Components/Ansaetze/Ansaetze.css
  src/Components/Ansaetze/Ansaetze.js
  src/Components/Vergleich/Vergleich.css
Labels: Projektwebseite

#186 batch bug fixes PR
  src/Components/About/About.css
  src/Components/About/About.js
  src/Components/Fragebogen/Fragebogen.js
  src/Components/Home/Home.js
  src/Components/TeamContribution/TeamContribution.css
  src/Components/TeamContribution/TeamContribution.js
Labels: Projektwebseite, bug

#189 added content from the data privacy concept group
  src/Components/About/About.css
  src/Components/Ansaetze/Ansaetze.css
  src/Components/CoronaWarnApp/CoronaWarnApp.css
  src/Components/CoronaWarnApp/CoronaWarnApp.js
Labels: Projektwebseite
